server:
    port: 88
    servlet:
        context-path: /
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/example_security?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root
    redis:
        database: 0
        host: 192.168.3.128
        password: m5dAyo5Hm5kG
        port: 6379
mybatis-plus:
    configuration:
        log-impl: com.example.common.service.impl.MybatisPlusLogImpl
config:
    enable-ansi: true
    request-log-format: true
    response-log-format: true
    login:
        token-valid-time: 60
