############################# 访问路径、端口 TOMCAT START ############################
server:
    port: 8080
    servlet:
        context-path: /
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
        uri-encoding: UTF-8
############################# 访问路径、端口 TOMCAT END ##############################


################################ SPRING CONFIG START ###############################
spring:
    application:
        name: example
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    jackson:
        date-format: yyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    banner:
        charset: UTF-8
        location: classpath:config/banner.txt
    thymeleaf:
        cache: false


# 当前项目maven激活环境，例如：local/test/prod，对应pom.xml中profile设置值
---
spring:
    profiles:
        active: '@profileActive@'
################################ SPRING CONFIG END ################################


################################## CONFIG START ###################################
config:
    # JWT 配置
    jwt:
        header: token
        secret: 'w(ﾟДﾟ)w'
        issuer: example
        subject: key
        audience: web
        expire-minutes: 60
################################## CONFIG END ######################################


############################### MYBATIS-PLUS START #################################
mybatis-plus:
    check-config-location: true
    configuration:
        map-underscore-to-camel-case: true
    global-config:
        db-config:
            id-type: id_worker
            logic-delete-value: 0
            logic-not-delete-value: 1
    mapper-locations: classpath*:mapper/**/*Mapper.xml
################################ MYBATIS-PLUS END #################################


############################### DRUID数据源配置 start ##############################
---
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            filter:
                slf4j:
                    enabled: true
                stat:
                    log-slow-sql: true
                    merge-sql: true
                    slow-sql-millis: 3000
                wall:
                    config:
                        delete-allow: true
                        drop-table-allow: false
                    enabled: true
            filters: stat,wall,slf4j
            initial-size: 10
            max-active: 100
            max-pool-prepared-statement-per-connection-size: 20
            max-wait: 60000
            min-evictable-idle-time-millis: 300000
            min-idle: 10
            pool-prepared-statements: true
            stat-view-servlet:
                enabled: true
                login-password: druid123
                login-username: druid
                url-pattern: /druid/*
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            validation-query: SELECT 1 FROM DUAL
        type: com.alibaba.druid.pool.DruidDataSource
################################ DRUID数据源配置 END ################################


################################ REDIS 公共配置 START ###############################
---
spring:
    redis:
        jedis:
            pool:
                max-active: 2000
                max-wait: -1ms
                min-idle: 8
                max-idle: 200
        timeout: 10s
        lettuce:
            pool:
                max-active: 200
                max-idle: 8
                max-wait: 10s
                min-idle: 2
            shutdown-timeout: 3s
################################ REDIS 公共配置 END ##################################


##################################### SWAGGER START ####################################
swagger:
    base:
        package: com.example
    contact:
        email: lifeorwar@gmail.com
        name: yuanzili
        url: ''
    description: ''
    title: example
    url: ''
    version: 1.0
##################################### SWAGGER END #####################################

#################################### 项目信息 START ####################################
info:
    project-group-id: '@project.groupId@'
    project-artifact-id: '@project.artifactId@'
    project-name: '@project.name@'
    project-final-name: '@project.build.finalName@'
    project-author: ${swagger.contact.name}
    project-description: '@project.description@'
    project-source-encoding: '@project.build.sourceEncoding@'
    project-spring-boot-version: '@spring-boot.version@'
    project-mybatis-plus-version: '@mybatis-plus-boot-starter.version@'
    project-version: '@project.version@'
#################################### 项目信息 END #####################################